version: "3.6"
services:
    app:
        build: .
        ports:
            - 5000:5000
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: "db"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "password"
        ports:
            - 3307:3306
        volumes:
            - ./init:/docker-entrypoint-initdb.d
            - db-data:/var/lib/mysql
volumes:
    db-data:
networks:
    default:
        name: ict_net
        external: true
